apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-k8s-deployment
  namespace: deployment1
spec:
  selector:
    matchLabels:
      app: angular-k8s-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-k8s-deployment
    spec:
      containers:
      - name: angular-k8s-deployment
        image: fatmamrabet/angular-app:v6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-service
  namespace: deployment1
  labels:
    name: angular-k8s-deployment
spec:
  ports:
  - nodePort: 30170
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: angular-k8s-deployment
  type: NodePort